# Generated by Django 4.2.26 on 2026-04-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=1500.0),
        ),
        migrations.AlterField(
            model_name='ratinghistory',
            name='rating',
            field=models.FloatField(),
        ),
    ]
